### ISSUE TITLE
Widgets don't draw correctly

### ISSUE THREAD

**Issue by CommanderRedYT** [0xFEEDC0DE64/esp-gui-lib#11]
Currently, currentDisplay->start() is called before currentDisplay->initScreen();.
https://github.com/0xFEEDC0DE64/esp-gui-lib/blob/e953ec9216f7d8c5fc36592e91406dce557d4268/src/screenmanager.h#L31-L35

On the other hand, some widgets create a white border when start() is called.
https://github.com/0xFEEDC0DE64/esp-gui-lib/blob/e953ec9216f7d8c5fc36592e91406dce557d4268/src/widgets/progressbar.cpp#L15-L19

currentDisplay->initScreen() just fills the whole Screen with TFT_BLACK.

This means, things like white borders will be overdrawn with TFT_BLACK.

**Comment by CommanderRedYT** [comment]
A valid fix would be to call currentDisplay->initScreen() before currentDisplay->start()

**Comment by 0xFEEDC0DE64** [comment]
Widget::start should only be called from Display::initScreen

**Comment by CommanderRedYT** [comment]
Oh okay, but still, currentDisplay->initScreen() only fills the screen black
